### PR TITLE
Null Safety migration

### PR DESCRIPTION
**Pull request by domesticmouse**
Hi!

I'm in the process of migrating some of my packages to Null Safety, and I have your package as an indirect dependency.

I have made an initial migration of your package, and I'm hoping you could have a look and let me know of what you think of this PR? Please let me know what else needs to be done to this PR to bring it up to mergable status?

Thanks!

brett

### CODE REVIEW

**Comment by mzdm** [comment]
Hey, @domesticmouse I see you closed this. Does this mean this package is not maintained anymore? 😕
It's a dev dependency of `google_fonts` package (used in generator).

**Comment by domesticmouse** [comment]
@mzdm I'm not a maintainer on this project. I closed this PR out as it hasn't seen any action from the project owner. Happy to re-open if the project owner wants to merge it and release a null safe version of this library.

**Comment by mzdm** [comment]
I see. I saw some people from Google on the contributions list so I thought and you as a Flutter/Google member team perhaps had more info. 👍

**Comment by kendfinger** [comment]
Thanks! I just merged this after review.

**Pull request merged**
