### PR TITLE
First Dart 2 compliant release

### PR DESCRIPTION
**Pull request by chalin**
- Bump version to 3.0.0
- Fix type errors
- Ignore `.dart_tool`
- Fix tests
- Enable Travis CI

cc @filiph @kwalrath @kevmoo 

Related: https://github.com/filiph/linkcheck/issues/12

### CODE REVIEW

**Comment by chalin** [comment]
Travis is happy: https://travis-ci.org/chalin/console.dart/builds/391321124

@kaendfinger - can this PR be merged soon?

**Comment by Pacane** [comment]
Do you guys use this internally or what?

**Comment by chalin** [comment]
It is used by https://github.com/filiph/linkcheck, which we use to check the links for https://github.com/dart-lang/site-www and https://github.com/dart-lang/site-webdev.

**Comment by kaendfinger** [comment]
Glad to see this library being used! I forgot I even made it to be completely honest.
I approve of the changes as well. In fact, I'm considering picking back up on development of it.

**Comment by kaendfinger** [comment]
@chalin I have publish v3.0.0 to Pub. Let me know if I can be of any help.

**Comment by chalin** [comment]
Thanks!

**Pull request merged**
